# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Group name", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "members",
                    models.JSONField(default=list, help_text="List of user IDs"),
                ),
                (
                    "assigned_agents",
                    models.JSONField(
                        default=list,
                        help_text="List of agent IDs assigned to this group",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this group"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="groups_grou_name_0806de_idx"),
                    models.Index(
                        fields=["created_by"], name="groups_grou_created_8ed5a1_idx"
                    ),
                ],
            },
        ),
    ]
