# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        # Add tenant field
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this group belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='groups',
                to='tenants.tenant',
                db_index=True,
                null=True  # Temporarily nullable for migration
            ),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_name_0806de_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_created_8ed5a1_idx',
        ),
        # Add new indexes with tenant
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'name'], name='groups_grp_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'created_by'], name='groups_grp_tenant_cby_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'is_active'], name='groups_grp_tenant_act_idx'),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tenant', 'name')},
        ),
    ]
