# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Tool name", max_length=255)),
                ("description", models.TextField(help_text="Tool description")),
                ("code", models.TextField(help_text="Python code for the tool")),
                (
                    "dependencies",
                    models.JSONField(
                        default=list, help_text="Python package dependencies"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this tool"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="tools_tool_name_3f7e14_idx"),
                    models.Index(
                        fields=["created_by"], name="tools_tool_created_0b52e2_idx"
                    ),
                ],
            },
        ),
    ]
