# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        # Add tenant field
        migrations.AddField(
            model_name='tool',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this tool belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tools',
                to='tenants.tenant',
                db_index=True,
                null=True  # Temporarily nullable for migration
            ),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='tool',
            name='tools_tool_name_3f7e14_idx',
        ),
        migrations.RemoveIndex(
            model_name='tool',
            name='tools_tool_created_0b52e2_idx',
        ),
        # Add new indexes with tenant
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tenant', 'name'], name='tools_tool_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tenant', 'created_by'], name='tools_tool_tenant_cby_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tenant', 'is_active'], name='tools_tool_tenant_act_idx'),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('tenant', 'name')},
        ),
    ]
