# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django_tenants.models import TenantMixin, DomainMixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Primary admin contact email (visible to superadmin)', max_length=254)),
                ('admin_name', models.CharField(blank=True, help_text='Name of primary admin/point of contact (visible to superadmin)', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1001+', '1001+ employees')], help_text='Company size (for analytics)', max_length=20, null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry/sector (for analytics)', max_length=100, null=True)),
                ('license_type', models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', help_text='Current license tier', max_length=20)),
                ('license_limits', models.JSONField(blank=True, default=dict, help_text='License limits based on tier')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('subscription_current_period_end', models.DateTimeField(blank=True, null=True)),
                ('storage_used_mb', models.IntegerField(default=0, help_text='Storage used in MB')),
                ('messages_this_month', models.IntegerField(default=0, help_text='Messages sent this billing period')),
                ('last_usage_reset', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Tenant is active')),
                ('is_trial', models.BooleanField(default=True, help_text='Tenant is in trial period')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('features_enabled', models.JSONField(blank=True, default=dict, help_text='Feature toggles for this tenant')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('integrations', models.JSONField(blank=True, default=dict, help_text='Third-party integration configurations')),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], default='user', help_text="User's role within this tenant", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Membership is active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to='users.user')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email to send invitation to', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('invited_by', models.UUIDField(help_text='User ID who sent invitation')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['license_type'], name='tenants_ten_license_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_status'], name='tenants_ten_subscri_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'user'], name='tenants_ten_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='tenants_ten_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['email', 'status'], name='tenants_ten_email_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token'], name='tenants_ten_token_idx'),
        ),
    ]
