# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="MCP server name", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "command",
                    models.CharField(
                        help_text="Command to run (e.g., npx)", max_length=255
                    ),
                ),
                ("args", models.JSONField(default=list, help_text="Command arguments")),
                (
                    "env",
                    models.JSONField(default=dict, help_text="Environment variables"),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this MCP server"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="mcp_mcpserv_name_601702_idx"),
                    models.Index(
                        fields=["created_by"], name="mcp_mcpserv_created_a453f5_idx"
                    ),
                ],
            },
        ),
    ]
