# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('mcp', '0001_initial'),
    ]

    operations = [
        # Add tenant field
        migrations.AddField(
            model_name='mcpserver',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this MCP server belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mcp_servers',
                to='tenants.tenant',
                db_index=True,
                null=True  # Temporarily nullable for migration
            ),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='mcpserver',
            name='mcp_mcpserv_name_601702_idx',
        ),
        migrations.RemoveIndex(
            model_name='mcpserver',
            name='mcp_mcpserv_created_a453f5_idx',
        ),
        # Add new indexes with tenant
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['tenant', 'name'], name='mcp_mcps_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['tenant', 'created_by'], name='mcp_mcps_tenant_cby_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['tenant', 'is_active'], name='mcp_mcps_tenant_act_idx'),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='mcpserver',
            unique_together={('tenant', 'name')},
        ),
    ]
