# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(
                    help_text='Tenant this message belongs to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='tenants.tenant',
                    db_index=True
                )),
                ('group', models.UUIDField(help_text='Group ID this message belongs to')),
                ('sender_type', models.CharField(
                    max_length=20,
                    choices=[('user', 'User'), ('agent', 'Agent')],
                    help_text='Who sent the message'
                )),
                ('sender_id', models.UUIDField(help_text='User or Agent ID')),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'group', 'created_at'], name='msgs_msg_tenant_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'sender_id'], name='msgs_msg_tenant_sid_idx'),
        ),
    ]
