# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.UUIDField(help_text="Group ID this document belongs to"),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=500),
                ),
                (
                    "storage_path",
                    models.CharField(
                        help_text="Path in storage (MinIO/S3)", max_length=1000
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="MIME type", max_length=100)),
                ("uploaded_by", models.UUIDField(help_text="User ID who uploaded")),
                (
                    "embeddings_indexed",
                    models.BooleanField(
                        default=False, help_text="Whether embeddings are in Qdrant"
                    ),
                ),
                (
                    "qdrant_collection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["group", "created_at"],
                        name="documents_d_group_6b093c_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="documents_d_uploade_970571_idx"
                    ),
                ],
            },
        ),
    ]
