# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        # Add tenant field
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this document belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents',
                to='tenants.tenant',
                db_index=True,
                null=True  # Temporarily nullable for migration
            ),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_group_6b093c_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_uploade_970571_idx',
        ),
        # Add new indexes with tenant
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'group', 'created_at'], name='docs_doc_tenant_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'uploaded_by'], name='docs_doc_tenant_uby_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'embeddings_indexed'], name='docs_doc_tenant_emb_idx'),
        ),
    ]
