# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.UUIDField(help_text="Tenant ID")),
                ("user", models.UUIDField(blank=True, help_text="User ID", null=True)),
                (
                    "action",
                    models.CharField(
                        help_text="Action type (e.g., 'message_sent', 'agent_created')",
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Resource type (e.g., 'agent', 'message')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(blank=True, help_text="Resource ID", null=True),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="analytics_u_tenant_f880e4_idx",
                    ),
                    models.Index(
                        fields=["action"], name="analytics_u_action_7a1e8c_idx"
                    ),
                    models.Index(fields=["user"], name="analytics_u_user_02ccc0_idx"),
                ],
            },
        ),
    ]
