# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of this stats snapshot')),
                ('total_users', models.IntegerField(default=0, help_text='Total users in tenant')),
                ('active_users_today', models.IntegerField(default=0, help_text='Users who logged in today')),
                ('new_users_today', models.IntegerField(default=0, help_text='Users created today')),
                ('total_agents', models.IntegerField(default=0, help_text='Total agents created')),
                ('new_agents_today', models.IntegerField(default=0, help_text='Agents created today')),
                ('total_mcp_servers', models.IntegerField(default=0, help_text='Total MCP servers')),
                ('total_tools', models.IntegerField(default=0, help_text='Total tools')),
                ('total_groups', models.IntegerField(default=0, help_text='Total groups')),
                ('active_groups_today', models.IntegerField(default=0, help_text='Groups with activity today')),
                ('messages_sent_today', models.IntegerField(default=0, help_text='Messages sent today')),
                ('total_messages', models.IntegerField(default=0, help_text='Total messages (cumulative)')),
                ('documents_uploaded_today', models.IntegerField(default=0, help_text='Documents uploaded today')),
                ('total_documents', models.IntegerField(default=0, help_text='Total documents')),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0, help_text='Storage used in MB', max_digits=10)),
                ('storage_delta_mb', models.DecimalField(decimal_places=2, default=0, help_text='Storage change today (MB)', max_digits=10)),
                ('api_calls_today', models.IntegerField(default=0, help_text='Total API calls today')),
                ('estimated_revenue_today', models.DecimalField(decimal_places=2, default=0, help_text='Estimated revenue for today (based on usage)', max_digits=10)),
                ('tenant', models.ForeignKey(help_text='Tenant these stats belong to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Daily Stats',
                'verbose_name_plural': 'Tenant Daily Stats',
                'ordering': ['-date', 'tenant'],
            },
        ),
        migrations.CreateModel(
            name='GlobalPlatformStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of this stats snapshot', unique=True)),
                ('total_tenants', models.IntegerField(default=0, help_text='Total tenants on platform')),
                ('active_tenants', models.IntegerField(default=0, help_text='Tenants active today')),
                ('new_tenants_today', models.IntegerField(default=0, help_text='Tenants created today')),
                ('paying_tenants', models.IntegerField(default=0, help_text='Tenants with paid subscriptions')),
                ('trial_tenants', models.IntegerField(default=0, help_text='Tenants in trial')),
                ('total_users', models.IntegerField(default=0, help_text='Total users across all tenants')),
                ('active_users_today', models.IntegerField(default=0, help_text='Active users today')),
                ('new_users_today', models.IntegerField(default=0, help_text='New users today')),
                ('total_agents', models.IntegerField(default=0, help_text='Total agents created')),
                ('total_groups', models.IntegerField(default=0, help_text='Total groups')),
                ('total_mcp_servers', models.IntegerField(default=0, help_text='Total MCP servers')),
                ('total_tools', models.IntegerField(default=0, help_text='Total tools')),
                ('messages_today', models.IntegerField(default=0, help_text='Messages processed today')),
                ('total_messages', models.BigIntegerField(default=0, help_text='Total messages (cumulative)')),
                ('api_calls_today', models.IntegerField(default=0, help_text='API calls today')),
                ('total_storage_used_gb', models.DecimalField(decimal_places=2, default=0, help_text='Total storage used across all tenants (GB)', max_digits=12)),
                ('total_revenue_today', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue today', max_digits=12)),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Monthly Recurring Revenue (MRR)', max_digits=12)),
                ('open_tickets', models.IntegerField(default=0, help_text='Open support tickets')),
                ('tickets_created_today', models.IntegerField(default=0, help_text='Tickets created today')),
                ('tickets_resolved_today', models.IntegerField(default=0, help_text='Tickets resolved today')),
            ],
            options={
                'verbose_name': 'Global Platform Stats',
                'verbose_name_plural': 'Global Platform Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Ticket subject', max_length=255)),
                ('description', models.TextField(help_text='Issue description')),
                ('raised_by_email', models.EmailField(help_text='Email of user who raised ticket', max_length=254)),
                ('raised_by_name', models.CharField(help_text='Name of user who raised ticket', max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical Issue'), ('feature_request', 'Feature Request'), ('bug', 'Bug Report'), ('account', 'Account Management'), ('other', 'Other')], default='other', max_length=50)),
                ('assigned_to', models.EmailField(blank=True, help_text='Superadmin email assigned to this ticket', max_length=254, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Internal resolution notes')),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Time to first response (hours)', max_digits=8, null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that raised this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='tenantstats',
            index=models.Index(fields=['tenant', 'date'], name='analytics_ts_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantstats',
            index=models.Index(fields=['date'], name='analytics_ts_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status'], name='analytics_st_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='analytics_st_status_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='analytics_st_created_idx'),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='tenantstats',
            unique_together={('tenant', 'date')},
        ),
    ]
