# Generated by Django 5.0.14 on 2025-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Agent name", max_length=255)),
                ("description", models.TextField(help_text="Agent description")),
                ("emoji", models.CharField(default="🤖", max_length=10)),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Google Gemini"),
                            ("ollama", "Ollama"),
                        ],
                        default="openai",
                        help_text="LLM provider",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        help_text="LLM model name (e.g., gpt-4o, claude-sonnet-4.5)",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt for the agent", null=True
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration (temperature, max_tokens, etc.)",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this agent"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="agents_agen_name_26b7c8_idx"),
                    models.Index(
                        fields=["llm_provider"], name="agents_agen_llm_pro_46d3f2_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="agents_agen_created_ad9db7_idx"
                    ),
                ],
            },
        ),
    ]
