# Generated by Django 4.2 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        # Add tenant field
        migrations.AddField(
            model_name='agent',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this agent belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='agents',
                to='tenants.tenant',
                db_index=True,
                null=True  # Temporarily nullable for migration
            ),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_name_26b7c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_llm_pro_46d3f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_created_ad9db7_idx',
        ),
        # Add new indexes with tenant
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'name'], name='agents_agen_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'llm_provider'], name='agents_agen_tenant_llm_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'created_by'], name='agents_agen_tenant_cby_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'is_active'], name='agents_agen_tenant_act_idx'),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('tenant', 'name')},
        ),
    ]
